dist: trusty

language: python

python:
  - 3.8

before_install: skip

install:
  # install the package
  - pip install -U pip
  # - pip install --progress-bar off -r requirements.txt
  - pip install --progress-bar off -r dev_requirements.txt
  # - pip install .
  - pip install "git+https://github.com/AI4SCR/scQUEST.git@master"

script:
  # test import
  - python -c "import scQUEST"

  # run unit tests
  - python -m pytest -sv --cov=scQUEST --cov-fail-under=65

  # static type checking
  - python -m mypy scQUEST

  # style checking
  - python -m black scQUEST --check --diff --color
  - python -m flake8 --per-file-ignores="__init__.py:F401" scQUEST

# the following stages only start if the "test" stage above all succeed
jobs:
  include:
    - stage: Documentation
      python: 3.8
      before_install: skip
      install:
        - pip install --progress-bar off -r dev_requirements.txt
        - pip install "git+https://github.com/AI4SCR/scQUEST.git@master"
      #        - pip install umap-learn
      before_script:
        - jupyter-nbconvert --to markdown --output-dir docs/ ./tutorials/Custom_models.ipynb
        - jupyter-nbconvert --to markdown --output-dir docs/ ./tutorials/scQUEST_tutorial.ipynb
      script:
        # build documentation pages
        - cd docs && make html && cd ..
      deploy:
        - provider: pages
          skip_cleanup: true
          #          github_url: github.ibm.com  # defaults to github.com
          repo: AI4SCR/scQUEST
          github_url: github.com
          #          github_token: $GITHUB_TOKEN
          github_token: $travis_scQUEST
          local_dir: docs/_build/html
          on:
            branch: master

notifications:
  slack:
    rooms:
      - ibm-research:gDY3T1BRb0QNaUVbDEhcTQGs
    on_success: never
    on_failure: always
